// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5QLEHVst9Uv58guB7V9-UGNXn9C4u_PA',
    appId: '1:502548495564:android:79dbd1d39a1856d76c9669',
    messagingSenderId: '502548495564',
    projectId: 'quickbite-daf1e',
    storageBucket: 'quickbite-daf1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnTU_492ZLbM09kTUUJEQKa4F36Dw3xjc',
    appId: '1:502548495564:ios:d1134cc45ea100646c9669',
    messagingSenderId: '502548495564',
    projectId: 'quickbite-daf1e',
    storageBucket: 'quickbite-daf1e.firebasestorage.app',
    iosBundleId: 'com.example.quickBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnTU_492ZLbM09kTUUJEQKa4F36Dw3xjc',
    appId: '1:502548495564:ios:d1134cc45ea100646c9669',
    messagingSenderId: '502548495564',
    projectId: 'quickbite-daf1e',
    storageBucket: 'quickbite-daf1e.firebasestorage.app',
    iosBundleId: 'com.example.quickBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1S5xS9hiQYCqbKvjMCm_WuflBwrOwuTs',
    appId: '1:502548495564:web:2f44e4b189e621176c9669',
    messagingSenderId: '502548495564',
    projectId: 'quickbite-daf1e',
    authDomain: 'quickbite-daf1e.firebaseapp.com',
    storageBucket: 'quickbite-daf1e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1S5xS9hiQYCqbKvjMCm_WuflBwrOwuTs',
    appId: '1:502548495564:web:2f44e4b189e621176c9669',
    messagingSenderId: '502548495564',
    projectId: 'quickbite-daf1e',
    authDomain: 'quickbite-daf1e.firebaseapp.com',
    storageBucket: 'quickbite-daf1e.firebasestorage.app',
  );

}